### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by bryanhuntesl** [bragful/ephp#13]
I'd like to write an adaptor by means of which ephp could be used as a rendering library for Phoenix / Raxx / Cowboy / whatever - but I noticed the LGPL license - 99% of Erlang/Elixir everything is Apache 2 licensed. I'm not sure what the implications of LGPL/Apache is but it could be a stumbling block. 

Stackoverflow has some rambling description - but I think I need a flowchart to grok it 😂

https://opensource.stackexchange.com/questions/5664/linking-from-lgpl-2-1-software-to-apache-2-0-library

Anyhow, my question is, considering you're the committer with the exception of a single commit, are you fully committed to LGPL or would you consider Apache 2 licensing?

**Comment by manuel-rubio** [comment]
I guess the licenses have importance to avoid to ask the author all the time about what's let to do. But even MySQL had a double license in the same way other software has. In the end, the author can do whatever he wants to do.

From my point of view if you want to use ephp, keeping in mind you're using it as is, you only need to release your product saying you're using it, putting a link to the place where it's and if you perform some modification, please, create a fork and a pull request. That's all. LGPL is clear about these obligations, Apache let you avoid them.

Maybe I'm wrong or ignoring something, not sure :-P

**Comment by bryanhuntesl** [comment]
I could be totally wrong - and bear in mind I'm only thinking about it this morning as an idea of something that would be cool. Cowboy already has a mature [Django like](https://github.com/erlydtl/erlydtl) templating system, and Elixir has [EEx (very similar)](https://hexdocs.pm/eex/EEx.html).

Anyhow what I suspect, is that if I introduced ephp as a dependency, and I released my (open-source) library - then the license for that libary would need to be LGPL, and so on for any derivative works.

Again, I don't really know, like I said, most everything else is Apache. I'm not a lawyer but just thought it could be a stumbling block. Anyhow, totally respect your choice.

**Comment by manuel-rubio** [comment]
No, it shouldn't. If you keep ephp as external (not included in your code) only referred in your rebar.config file, you can do whatever you want. Even create a close code. LGPL let you do that. The "problem" is if you want to modify and/or including ephp inside of your code.

**Comment by bryanhuntesl** [comment]
Ah that's cool then - perfect !
