### ISSUE TITLE
`Ephp.eval` always fails with `no case clause matching` error

### ISSUE THREAD

**Issue by osbre** [bragful/ephp#15]
## Expected Behavior
`out` variable from `out = EphpContext.get_output(ctx)` contains `hello worldthis is awesome`

https://github.com/osbre/ephp_web/blob/main/lib/ephp_web/ephp_plug.ex#L34

## Actual Behavior
getting an error 👀 

```bash
** (CaseClauseError) no case clause matching: {:EXIT, {:function_clause, [{:ephp_interpr, :run, [#Reference<0.4106486204.4208197636.168118>, {:{}, [], [:print_text, "hello world\n", {{:line, 1}, {:column, 2}}]}, false], [file: ~c"/home/o/code/ephp_web/deps/ephp/src/ephp_interpr.erl", line: 77]}, {:lists, :foldl, 3, [file: ~c"lists.erl", line: 1350]}, {:ephp_interpr, :process, 3, [file: ~c"/home/o/code/ephp_web/deps/ephp/src/ephp_interpr.erl", line: 25]}, {:ephp, :eval, 3, [file: ~c"/home/o/code/ephp_web/deps/ephp/src/ephp.erl", line: 182]}, {EphpWeb.EphpPlug, :call, 2, [file: ~c"lib/ephp_web/ephp_plug.ex", line: 34]}, {Bandit.Pipeline, :call_plug, 2, [file: ~c"lib/bandit/pipeline.ex", line: 110]}, {Bandit.Pipeline, :run, 6, [file: ~c"lib/bandit/pipeline.ex", line: 25]}, {Bandit.HTTP1.Handler, :handle_data, 3, [file: ~c"lib/bandit/http1/handler.ex", line: 27]}]}}
```

![message from the terminal window](https://github.com/bragful/ephp/assets/23292709/7d661e30-34de-42ce-825f-20ddcb275fda)

## Steps to Reproduce the Problem

Linked GitHub repository to easily reproduce the problem: https://github.com/osbre/ephp_web

  1. `git clone git@github.com:osbre/ephp_web.git && cd ephp_web`
  2. `mix deps.get`
  3. `mix run --no-halt`
  4. `curl http://0.0.0.0:4000`
  5. Check the output from command 3

## Specifications

  - Version:
  	- ephp: latest from the master branch, therefore commit https://github.com/bragful/ephp/commit/d32fc68875160ef31f30f72e93b0a8741d6e9ae2
  		- same result with 0.3.1 from Hex.
  	- Elixir 1.15.0 (compiled with Erlang/OTP 25)
  	- Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
  - Platform: Linux
  - Subsystem: Linux Mint 21 with `5.15.0-75-generic` kernel

**Comment by manuel-rubio** [comment]
@osbre if you remove the following line it should work perfectly fine:
```elixir
      |> Macro.escape()
```
Remember that the _parse_ for ePHP isn't a parse in the sense of Elixir, or Erlang. It's only a tokenization of the PHP code, and it shouldn't be modified.

**Comment by osbre** [comment]
Thank you! It solved my problem
