### ISSUE TITLE
Weird atanh implementation...

### ISSUE THREAD

**Issue by manuel-rubio** [bragful/ephp#8]
The return for `atanh` in Erlang is based on the math C library and depending on the OS it is different even giving results. Because of that:

```erlang
php_atanh(_Context, _Line, {_, Number}) ->
    % math:atanh(Number); % FIXME: the implementation is not reliable
    1 / 2 * math:log((1 + Number) / (1 - Number)).
```

Any idea? Should we have to keep it as is?

**Comment by Girgias** [comment]
Just discovered this project, but this shouldn't be a problem as PHP also uses the underlying C function as of PHP 8.0 all the time since officially requiring C99.

**Comment by manuel-rubio** [comment]
Indeed the problem is because I wanted a deterministic way of getting atanh. Using that method is working and giving the same results for Windows, Mac, and GNU/Linux. I'm going to close the ticket and remove the FIXME comment.
